### ISSUE TITLE
keeps on saying the app has not been consented 

### ISSUE THREAD

**Issue by daxu7509** [Azure-Samples/active-directory-dotnet-native-headless#12]
I am trying to use your github sample (active-directory-dotnet-native-headless), however, it gives me this error message:

AADSTS65001: The user or administrator has not consented to use the application with ID 'e908c64f-f899-4187-acbb-385899d1e9ba'. Send an interactive authorization request for this user and resource.
Trace ID: 9b22c679-79bb-4a9f-944e-bc05a7ee330a
Correlation ID: bf677c3b-91ce-40d6-b620-f2f097c190d3
Timestamp: 2016-10-20 14:53:31Z

I believe that I following your steps as careful as possible, so anything I am still missing? Is there some kind of setting I need to change?

What I do to consent it?

Many Thanks

**Comment by Injac** [comment]
I have exactly the same problem. The scenario that we have is, that we need to authenticate users within multiple console-based apps, or a service for example. A similar approach can be used in Node.js to solve this problem:
 
```
`var adal = require('adal-node');
  var AuthenticationContext = adal.AuthenticationContext;
  var authorityUrl = request.authorityHostUrl + '/' + request.tenant;
  var resource = '00000002-0000-0000-c000-000000000000';
  var context = new AuthenticationContext(authorityUrl);

  context.acquireTokenWithUsernamePassword(resource, request.username, request.password, request.clientId, function(err, tokenResponse) {
    console.log(tokenResponse);
    if (err) { // auth failed, not sure of err value so forcing 1/0 here
      process.exit(1);
    } else {
      process.exit(0);
    }
});`
```

This works perfectly fine (every time) without any errors. I wonder why this is not possible in C#/.NET. The only option is to check the source of ADAL .NET to see why all of this fails (for now). On the other hand an end to end example with all the required perquisites explained in detail would be helpful as well.

**Comment by Ro3A** [comment]
I'm running into the same issue. I've tried every possible permutation of credentials, with and without ADAL library, azure configurations, accounts types (non-interactive etc), user / password credentials, client credentials. I've also found and article that alludes to Web API not supporting a non-interactive flow. 

Here's our exact scenario:

We have an azure app service that serves our customer portal where our clients can access invoices etc. This app is external facing and uses individual user accounts via AspNet Identity. It is not integrated with AD. As for CRM / AD - we are a single tenant. We need to create / update records in CRM from customer portal via a new app service. We can do this with the OrganizationService easily but would prefer to go ahead and use the new CRM web api since we are starting with a clean slate. 

I'm hoping to have an authoritative source tell me simply if it's possible to use CRM web api without any user interaction in a single tenant scenario. It seems like we're close if we can just grant consent...

**Comment by dstrockis** [comment]
I'm pretty sure this is due to the issue Vittorio describes here: http://www.cloudidentity.com/blog/2016/10/04/provision-an-app-created-on-portal-azure-com-in-your-own-tenant/

**Comment by Ro3A** [comment]
Thanks for the link. I'll have some time to try it this week. On a somewhat related note, the CRM Sdk is not compatible with .net core yet (netCoreApp specifically). Do you have an idea of when we'll see a compatible SDK?

**Comment by jamescro** [comment]
I'm still having this problem even after following the steps in Vittorio's blog post.

**Comment by stevex64** [comment]
I'm getting the same error as well, having gone through everything that has been suggested above as well as I know how.

**Comment by mathieuvalli** [comment]
After the step to configure permissions, try hitting "Grant Permissions" button in "Required permissions" section

**Comment by jmprieur** [comment]
Indeed you need to grant permissions. Since this is about flows without a web browser, the user cannot consent during the authentication. this needs to be done in the Azure portal (step 9 of the TodoListService app registration). See also https://github.com/Azure-Samples/active-directory-dotnet-native-headless#troubleshooting

**Comment by An0d** [comment]
Hi, i'm encountering this issue but don't find the "step 9 of the TodoListService app registration"
No more documentation on how to solve this issue ...

Please help ?

Thank you

**Comment by jmprieur** [comment]
@An0d : I just fixed the readme.md. the step (8 really) of the registration of the client app (second typo) was missing. Please have a look again at https://github.com/Azure-Samples/active-directory-dotnet-native-headless#troubleshooting

**Comment by An0d** [comment]
@jmprieur : Thank you for the correction ;-)
In the meantime, I found the solution, thanks anyway ;-)

**Comment by jmprieur** [comment]
@An0d thanks for reporting and for the update!
