### ISSUE TITLE
Error calling 'authContext.AcquireTokenAsync()'

### ISSUE THREAD

**Issue by radsolution** [Azure-Samples/active-directory-dotnet-native-headless#16]
Hello,
I'm trying to use this sample to authenticate a user in my B2C tenant,
but keep getting an error at line 164:
`"unknown_user_type: Unknown User Type"` HResult=**-2146233088**

If you require further info, please ask.

**Comment by cBashTN** [comment]
I think it does not work because **B2C does not support this** ...yet. Maybe tomorrow?  

See [https://feedback.azure.com/forums/169401-azure-active-directory/suggestions/13817784-add-support-for-resource-owner-password-credential](https://feedback.azure.com/forums/169401-azure-active-directory/suggestions/13817784-add-support-for-resource-owner-password-credential)

**Comment by jmprieur** [comment]
@parakhj : do you want to answer?

**Comment by parakhj** [comment]
That feature is super close to a private preview. if you are interested in trying out the preview, please upvote the feature that @cBashTN linked to. We will reach out there once it is available.

https://feedback.azure.com/forums/169401-azure-active-directory/suggestions/13817784-add-support-for-resource-owner-password-credential
